version: '3.8'

services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    volumes:
      - ./dataset:/docker-entrypoint-initdb.d/db.sql
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mediamingle
    ports:
      - "5432:5432"
    networks:
      - mediamingle
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: lvmehriban@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - mediamingle

  musicapp-service:
    container_name: mediamingle
    build:
      context: ./
    image: mediamingle
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL:  jdbc:postgresql://db:5432/mediamingle
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    volumes:
      - './:/src'
    networks:
      - mediamingle

volumes:
  db:
    driver: local
  pgadmin_data:

networks:
  mediamingle:
