version: '3.8'

services:
  db:
    container_name: postgres_container
    image: postgres
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bilobileto11
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    networks:
      - musicapp
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: lvmehriban@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - musicapp

  musicapp-service:
    container_name: music-app
    build:
      context: ./
    image: musicapp-demo
    depends_on:
      - db
#      - mongodb
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL:  jdbc:postgresql://db:5432/test
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: bilobileto11
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    volumes:
      - './:/src'
    networks:
      - musicapp

volumes:
  db:
    driver: local
  pgadmin_data:

networks:
  musicapp:
    external: true
