spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:postgresql://db:5432/mediamingle
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: lvmehriban@gmail.com
    password: qlgayhafotakvojj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


